windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-25T13:08:26'
      pinned: false
      title: vim go back to previous location - Google Search
      url: https://www.google.com/search?q=vim%20go%20back%20to%20previous%20location
    - active: true
      last_visited: '2021-05-25T13:08:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 360
      title: Vim - Go to previous location - Stack Overflow
      url: https://stackoverflow.com/questions/11018713/vim-go-to-previous-location
      zoom: 0.75
