windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-13T17:20:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Public holidays in Vietnam - Wikipedia
      url: https://en.wikipedia.org/wiki/Public_holidays_in_Vietnam
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-13T17:20:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: National Holidays in Vietnam in 2021 | Office Holidays
      url: https://www.officeholidays.com/countries/vietnam/2021
      zoom: 0.75
