windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-02T15:56:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 1086
      title: powerline-extra-symbols/README.md at master · ryanoasis/powerline-extra-symbols
      url: https://github.com/ryanoasis/powerline-extra-symbols/blob/master/README.md
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-02T16:07:01'
      pinned: false
      title: 256 font color - Google Search
      url: https://www.google.com/search?q=256%20font%20color
    - active: true
      last_visited: '2021-06-02T16:07:04'
      pinned: false
      scroll-pos:
        x: 0
        y: 2480
      title: 256 Colors - Cheat Sheet - Xterm, HEX, RGB, HSL
      url: https://jonasjacek.github.io/colors/
      zoom: 0.75
