windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-04-29T00:21:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-04-29T00:21:42'
      pinned: false
      title: remind linux x days from today - Google Search
      url: https://www.google.com/search?q=%20remind%20linux%20x%20days%20from%20today
    - active: true
      last_visited: '2021-04-29T00:21:58'
      pinned: false
      scroll-pos:
        x: 0
        y: 1040
      title: 'remind: examples/defs.rem | Fossies'
      url: https://fossies.org/linux/remind/examples/defs.rem
      zoom: 0.75
