windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-03T19:56:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 640
      title: linux check memory - Google Search
      url: https://www.google.com/search?q=linux%20check%20memory
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T19:57:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 5 Commands to Check Memory Usage in Linux {Easy Way}
      url: https://phoenixnap.com/kb/linux-commands-check-memory-usage
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-03T19:57:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 2400
      title: 5 Commands for Checking Memory Usage in Linux - Linux.com
      url: https://www.linux.com/training-tutorials/5-commands-checking-memory-usage-linux/
      zoom: 0.75
