windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-04T13:04:45'
      pinned: false
      title: ETF Hub | Financial Times
      url: https://etf.ft.com/
    - last_visited: '2021-05-04T13:05:48'
      pinned: false
      title: ETF Screener | Financial Times
      url: https://etf.ft.com/search/?q=spy&o=bm
    - active: true
      last_visited: '2021-05-04T13:06:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'SPY ETF: SPDR S&P 500 ETF - USD | Financial Times'
      url: https://etf.ft.com/funds/4942/
      zoom: 0.75
