windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAKyAAABjwAABUYAAALwAAACsgAAAY8AAAVGAAAC8AAAAAAAAAAABVYAAAKyAAAB
    jwAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-06T13:14:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-05-06T13:15:04'
      pinned: false
      title: awk some lines without delimitr - Google Search
      url: https://www.google.com/search?q=%20awk%20some%20lines%20without%20delimitr
    - last_visited: '2021-05-06T13:16:54'
      pinned: false
      title: awk sum lines without delimiter - Google Search
      url: https://www.google.com/search?q=awk+sum+lines+without+delimiter&spell=1&sa=X&ved=2ahUKEwix-eDas7TwAhUDVH0KHesvA1kQBSgAegQIARAw&biw=1821&bih=1005
    - last_visited: '2021-05-06T13:17:06'
      pinned: false
      title: 20 awk examples – Linux Hint
      url: https://linuxhint.com/20_awk_examples/
    - active: true
      last_visited: '2021-05-06T13:24:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 11049
      title: 20 awk examples – Linux Hint
      url: https://linuxhint.com/20_awk_examples/#a12
      zoom: 0.75
  - history:
    - last_visited: '2021-05-06T13:21:01'
      pinned: false
      title: awk starts with - Google Search
      url: https://www.google.com/search?q=awk%20starts%20with
    - active: true
      last_visited: '2021-05-06T13:21:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 1920
      title: awk statement to match all lines starting with "#"
      url: https://www.unix.com/shell-programming-and-scripting/121651-awk-statement-match-all-lines-starting.html
      zoom: 0.75
