windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-07T04:19:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: terminal.sexy - Terminal Color Scheme Designer
      url: http://terminal.sexy/
      zoom: 0.75
