windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAAGAAAAADwAAACAAAAKjAAABgAAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAAGA
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-04-28T22:22:31'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: 'Inbox: Todoist'
      url: https://todoist.com/app/project/2259674000
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-04-28T22:22:33'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: (2649) Feeder
      url: https://feeder.co/reader?logged_in=yes
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-04-28T22:22:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Bash check if process is running or not on Linux / Unix - nixCraft
      url: https://www.cyberciti.biz/faq/bash-check-if-process-is-running-or-notonlinuxunix/
      zoom: 0.75
