windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-26T17:45:06'
      pinned: false
      title: market cap - Google Search
      url: https://www.google.com/search?q=market%20cap
    - active: true
      last_visited: '2021-05-26T17:45:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 1520
      title: Market Capitalization Definition
      url: https://www.investopedia.com/terms/m/marketcapitalization.asp
      zoom: 0.75
