windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-01T13:14:22'
      pinned: false
      scroll-pos:
        x: 0
        y: 760
      title: Debloat Android – Chris Titus Tech
      url: https://christitus.com/debloat-android/
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-01T14:10:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 800
      title: 'husixu1/vimrc: A vim configuration (supports Termux)'
      url: https://github.com/husixu1/vimrc
      zoom: 0.75
    - last_visited: '2021-05-01T14:10:20'
      pinned: false
      title: 'husixu1/dotfiles-part: Some of my personal dotfiles.'
      url: https://github.com/husixu1/dotfiles-part
    - last_visited: '2021-05-01T14:10:17'
      pinned: false
      title: dotfiles-part/vim at master · husixu1/dotfiles-part
      url: https://github.com/husixu1/dotfiles-part/tree/master/vim
    - last_visited: '2021-05-01T14:10:08'
      pinned: false
      title: dotfiles-part/vimrc at master · husixu1/dotfiles-part
      url: https://github.com/husixu1/dotfiles-part/blob/master/vim/vimrc
