windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-26T19:35:40'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Market Capitalization Definition
      url: https://www.investopedia.com/terms/m/marketcapitalization.asp
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T19:35:41'
      pinned: false
      title: CFBK CF Bankshares Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=cfbk
    - active: true
      last_visited: '2021-05-26T19:36:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 40
      title: CFBK CF Bankshares Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=cfbk#statements
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T19:36:22'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ONCY Oncolytics Biotech Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=oncy
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T19:36:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 40
      title: NOA North American Construction Group Ltd. Stock Quote
      url: https://finviz.com/quote.ashx?t=noa
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T19:40:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: GDOT Green Dot Corporation Stock Quote
      url: https://finviz.com/quote.ashx?t=gdot
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T19:40:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: GCV The Gabelli Convertible and Income Securities Fund Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=gcv
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T20:04:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 439
      title: r readable numbers - Google Search
      url: https://www.google.com/search?q=r%20readable%20numbers
      zoom: 0.75
    - last_visited: '2021-05-26T20:04:16'
      pinned: false
      title: r - How to read scientific notation output (numbers that include "e")?
        - Cross Validated
      url: https://stats.stackexchange.com/questions/319637/how-to-read-scientific-notation-output-numbers-that-include-e
  - history:
    - last_visited: '2021-05-26T20:04:38'
      pinned: false
      title: r human readable numbers - Google Search
      url: https://www.google.com/search?q=r%20human%20readable%20numbers
    - active: true
      last_visited: '2021-05-26T20:04:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 80
      title: r - How to display numbers in a human readable format? - Stack Overflow
      url: https://stackoverflow.com/questions/14124167/how-to-display-numbers-in-a-human-readable-format
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T20:07:36'
      pinned: false
      title: r numbers with commas - Google Search
      url: https://www.google.com/search?q=r%20numbers%20with%20commas
    - active: true
      last_visited: '2021-05-26T20:07:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 962
      title: Display Large Numbers Separated with Comma in R (2 Example Codes)
      url: https://statisticsglobe.com/display-large-numbers-separated-with-comma-in-r
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T20:21:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: XHE SPDR S&P Health Care Equipment ETF Stock Quote
      url: https://finviz.com/quote.ashx?t=xhe
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T20:21:47'
      original-url: https://etf.com/XHE
      pinned: false
      scroll-pos:
        x: 0
        y: 400
      title: 'XHE ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/XHE
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T20:28:58'
      original-url: http://barchart.com/
      pinned: false
      title: Barchart.com | Commodity, Stock, and Currency Quotes, Charts, News &
        Analysis
      url: https://www.barchart.com/
    - active: true
      last_visited: '2021-05-26T20:49:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: SPY - S&P 500 SPDR ETF Price - Barchart.com
      url: https://www.barchart.com/etfs-funds/quotes/SPY/overview
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T20:29:52'
      pinned: false
      title: StockCharts.com | Advanced Financial Charts & Technical Analysis Tools
      url: https://stockcharts.com/
    - active: true
      last_visited: '2021-05-26T20:29:58'
      original-url: https://stockcharts.com/
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: SPY | SharpChart | StockCharts.com
      url: https://stockcharts.com/h-sc/ui?s=SPY
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T20:30:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 800
      title: average stock spread - Google Search
      url: https://www.google.com/search?q=average%20stock%20spread
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T20:32:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 1160
      title: average big-ask spread stock - Google Search
      url: https://www.google.com/search?q=average%20big-ask%20spread%20stock
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T20:36:03'
      pinned: false
      title: r average spread - Google Search
      url: https://www.google.com/search?q=r%20average%20spread
    - active: true
      last_visited: '2021-05-26T20:36:17'
      pinned: false
      scroll-pos:
        x: 0
        y: 520
      title: r average spread finance - Google Search
      url: https://www.google.com/search?q=r+average+spread+finance&ei=wk6uYP2uNdGQr7wP7reeCA&oq=r+average+spread+finance&gs_lcp=Cgdnd3Mtd2l6EAM6CAghEBYQHRAeUKxXWPFjYItlaABwAngAgAGbAYgB0AiSAQMwLjmYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=gws-wiz&ved=0ahUKEwj9l7TKu-fwAhVRyIsBHe6bBwEQ4dUDCBE&uact=5
      zoom: 0.75
  - history:
    - last_visited: '2021-05-26T20:37:37'
      pinned: false
      title: average spread formula - Google Search
      url: https://www.google.com/search?q=average%20spread%20formula
    - last_visited: '2021-05-26T20:38:32'
      pinned: false
      title: r average spread formula - Google Search
      url: https://www.google.com/search?q=r+average+spread+formula&ei=IE-uYLCdNcuFr7wP-K6DmAk&oq=r+average+spread+formula&gs_lcp=Cgdnd3Mtd2l6EAM6BAgAEA06CAgAEA0QBRAeOggIABAIEA0QHjoCCAA6BggAEBYQHlCMigNY-pwDYLqjA2gAcAJ4AIABfYgBtwSSAQMwLjWYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=gws-wiz&ved=0ahUKEwiwrZ33u-fwAhXLwosBHXjXAJMQ4dUDCBE&uact=5
    - last_visited: '2021-05-26T20:38:57'
      pinned: false
      title: r average spread quantmod - Google Search
      url: https://www.google.com/search?q=r+average+spread+quantmod&ei=V0-uYNmUG5vfmAWl6JqwCQ&oq=r+average+spread+quantmod&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOggIIRAWEB0QHlDdgQFYmrkBYJe7AWgAcAJ4AIABigGIAeMQkgEEMC4xOJgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwiZnKCRvOfwAhWbL6YKHSW0BpYQ4dUDCBE&uact=5
    - active: true
      last_visited: '2021-05-26T20:39:02'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: r average "spread" quantmod - Google Search
      url: https://www.google.com/search?q=r+average+%22spread%22+quantmod&sa=X&ved=2ahUKEwid3oadvOfwAhWsGKYKHYeWBmgQ5t4CMAB6BAgFEAY&biw=1781&bih=942&dpr=0.75
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-26T21:04:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: NOVT Novanta Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=novt
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-26T21:04:40'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: MCN Madison Covered Call & Equity Strategy Fund Stock Quote
      url: https://finviz.com/quote.ashx?t=mcn
      zoom: 0.75
