windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - active: true
    history:
    - last_visited: '2021-06-30T21:03:53'
      pinned: false
      title: Doom Emacs Configuration
      url: https://tecosaur.github.io/emacs-config/config.html#rebuild-mail-index
    - active: true
      last_visited: '2021-06-30T22:57:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
