windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAADwAABUYAAALwAAAADwAAAA8AAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    DwAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-04T14:11:46'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Stock Dividend Calendar | Ex Dividend Pay Date Calendar
      url: https://marketchameleon.com/Calendar/Dividend
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-04T14:11:46'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Dividend Calendar • 2021 • Updated Daily • Benzinga
      url: https://www.benzinga.com/calendars/dividends
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-04T14:11:46'
      pinned: false
      title: color
      url: https://emojipedia.org/search/?q=color
    - active: true
      last_visited: '2021-06-04T14:16:58'
      pinned: false
      scroll-pos:
        x: 0
        y: 80
      title: arrow
      url: https://emojipedia.org/search/?q=arrow
      zoom: 0.75
