windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - history:
    - last_visited: '2021-06-21T11:37:21'
      pinned: false
      title: HSBC Personal Banking - HSBC Bank USA
      url: https://www.us.hsbc.com/
    - last_visited: '2021-06-21T11:38:30'
      original-url: https://www.security.us.hsbc.com/gsa?idv_cmd=idv.SaaSSecurityCommand
      pinned: false
      title: 'Log on to Personal Internet Banking: Username | HSBC'
      url: https://www.security.us.hsbc.com/gsa/SECURITY_LOGON_PAGE/
    - last_visited: '2021-06-21T11:39:12'
      pinned: false
      title: Log on to Personal Internet Banking with password | HSBC
      url: https://www.security.us.hsbc.com/gsa/SECURITY_LOGON_PAGE/#
    - last_visited: '2021-06-21T11:39:20'
      original-url: https://www.us.hsbc.com/bin/saas/postback.html?url=/content/hsbc/us/en_us/online/dashboard.html&idv_cmd=idv.SaaSSecurityCommand
      pinned: false
      title: Your homepage | Banking | HSBC
      url: https://www.us.hsbc.com/online/dashboard/?rid=935
    - last_visited: '2021-06-21T11:39:44'
      original-url: https://www.us.hsbc.com/online/messages
      pinned: false
      title: Messages | Banking | HSBC
      url: https://www.us.hsbc.com/online/messages/
    - last_visited: '2021-06-21T11:40:09'
      original-url: https://www.us.hsbc.com/online/dashboard
      pinned: false
      title: Your homepage | Banking | HSBC
      url: https://www.us.hsbc.com/online/dashboard/
    - active: true
      last_visited: '2021-06-21T11:41:42'
      original-url: https://www.us.hsbc.com/bin/logout./content/hsbc/us/en_us/online-banking/log-off
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Log Off
      url: https://www.us.hsbc.com/online-banking/log-off/?rid=909
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-21T11:41:45'
      pinned: false
      title: Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:41:56'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/
    - last_visited: '2021-06-21T11:41:58'
      original-url: https://outlook.live.com/mail/0/inbox/
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:42:03'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIWdd30AAAA%3D
    - last_visited: '2021-06-21T11:42:08'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIWdd30AAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:42:08'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIWdd3wAAAA%3D
    - last_visited: '2021-06-21T11:42:34'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIWdd3wAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:42:34'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwkAAAA%3D
    - last_visited: '2021-06-21T11:42:40'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwkAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwgAAAA%3D
    - last_visited: '2021-06-21T11:42:42'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwgAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwcAAAA%3D
    - last_visited: '2021-06-21T11:42:46'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwcAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwkAAAA%3D
    - last_visited: '2021-06-21T11:43:08'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABIHVEwkAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:43:08'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQ0AAAA%3D
    - last_visited: '2021-06-21T11:43:09'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQ0AAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQwAAAA%3D
    - last_visited: '2021-06-21T11:43:15'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQwAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQsAAAA%3D
    - last_visited: '2021-06-21T11:43:29'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQsAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:43:29'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQ0AAAA%3D
    - last_visited: '2021-06-21T11:43:33'
      original-url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABHyLLQ0AAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-06-21T11:43:33'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/junkemail
    - last_visited: '2021-06-21T11:43:41'
      original-url: https://outlook.live.com/mail/0/junkemail
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/junkemail/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBIgAAABKhdE1MPkJJuq%2BLMFjFymoABIWdveoAAAA%3D
    - last_visited: '2021-06-21T11:43:42'
      original-url: https://outlook.live.com/mail/0/junkemail/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBIgAAABKhdE1MPkJJuq%2BLMFjFymoABIWdveoAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/junkemail
    - last_visited: '2021-06-21T11:43:47'
      original-url: https://outlook.live.com/mail/0/junkemail
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/junkemail/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBIgAAABKhdE1MPkJJuq%2BLMFjFymoABIHVX7gAAAA%3D
    - last_visited: '2021-06-21T11:43:48'
      original-url: https://outlook.live.com/mail/0/junkemail/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBIgAAABKhdE1MPkJJuq%2BLMFjFymoABIHVX7gAAAA%3D
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/junkemail
    - last_visited: '2021-06-21T11:43:50'
      original-url: https://outlook.live.com/mail/0/junkemail
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoALgAAA4lIdydTkERKv2ZG1Ybxqy4BABKhdE1MPkJJuq%2BLMFjFymoAAuVhpkYAAAA%3D
    - active: true
      last_visited: '2021-06-21T11:43:52'
      original-url: https://outlook.live.com/mail/0/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoALgAAA4lIdydTkERKv2ZG1Ybxqy4BABKhdE1MPkJJuq%2BLMFjFymoAAuVhpkYAAAA%3D
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
      zoom: 0.75
