windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-26T16:10:02'
      pinned: false
      title: vim delete surround quote - Google Search
      url: https://www.google.com/search?q=vim%20delete%20surround%20quote
    - active: true
      last_visited: '2021-05-26T16:10:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 480
      title: 'tpope/vim-surround: surround.vim: quoting/parenthesizing made simple'
      url: https://github.com/tpope/vim-surround
      zoom: 0.75
