windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAADwAABUYAAALwAAAAEAAAABAAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    EAAABUUAAALv
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-28T05:12:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 400
      title: emacs scroll down console output - Google Search
      url: https://www.google.com/search?q=emacs%20scroll%20down%20console%20output
      zoom: 0.75
