windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-03T21:42:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: wiki.manjaro.org
      url: https://wiki.manjaro.org/index.php/Pacman_Overview#Installing_Updates
      zoom: 0.75
