windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAKyAAAAIAAABUYAAALwAAACswAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAKzAAAA
    IQAABUUAAALv
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-19T03:47:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Gmail configuration (Mu4e 1.4.12 user manual)
      url: https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-19T03:47:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: emacs dired - Google Search
      url: https://www.google.com/search?q=emacs%20dired
      zoom: 0.75
