windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-10T15:38:20'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Last 100 filings received from Edgars
      url: https://whalewisdom.com/filing/latest_filings
      zoom: 0.75
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAANAAAAHgAABUYAAAL2AAAADQAAAB4AAAVGAAAC9gAAAAAAAAAABVYAAAANAAAA
    HgAABUYAAAL2
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-10T15:38:23'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
