windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - history:
    - active: true
      last_visited: '2021-07-01T12:03:58'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - history:
    - last_visited: '2021-07-01T12:04:11'
      pinned: false
      title: Outlook
      url: https://outlook.live.com/mail/0/inbox
    - last_visited: '2021-07-01T12:04:22'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/
    - last_visited: '2021-07-01T12:04:24'
      original-url: https://outlook.live.com/mail/0/inbox/
      pinned: false
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox
    - active: true
      last_visited: '2021-07-01T12:04:30'
      original-url: https://outlook.live.com/mail/0/inbox
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Mail - Mark Bojack - Outlook
      url: https://outlook.live.com/mail/0/inbox/id/AQMkADAwATM3ZmYAZS1kN2FkLWRkADVlLTAwAi0wMAoARgAAA4lIdydTkERKv2ZG1Ybxqy4HABKhdE1MPkJJuq%2BLMFjFymoAAAIBDAAAABKhdE1MPkJJuq%2BLMFjFymoABI3pFwoAAAA%3D
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-07-01T12:05:36'
      pinned: false
      title: Facebook - Đăng nhập hoặc đăng ký
      url: https://www.facebook.com/index.php?next=https%3A%2F%2Fwww.facebook.com%2Fconfirmcontact.php%3Fc%3D21451%26x%3D1%26z%3D0%26gfid%3DAQAnuzZfeE7ooUTdBqA
    - active: true
      last_visited: '2021-07-01T12:07:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Facebook – log in or sign up
      url: https://en-gb.facebook.com/index.php?next=https%3A%2F%2Fwww.facebook.com%2Fconfirmcontact.php%3Fc%3D21451%26x%3D1%26z%3D0%26gfid%3DAQAnuzZfeE7ooUTdBqA
      zoom: 0.75
