windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAAEAAAACEAAAKiAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAAAqIAAALv
  tabs:
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - active: true
    history: []
