windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-04T20:56:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: etf.ft.com
      url: https://etf.ft.com/funds/4942/
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-04T20:56:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: wiki.manjaro.org
      url: https://wiki.manjaro.org/index.php/Pacman_Overview#Installing_Updates
      zoom: 0.75
