windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-06-06T11:57:23'
      original-url: https://etf.com/splv
      pinned: false
      title: 'SPLV ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/SPLV
    - last_visited: '2021-06-06T11:58:30'
      pinned: false
      title: 'SPLV ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/SPLV#overview
    - last_visited: '2021-06-06T11:58:34'
      pinned: false
      title: 'SPLV ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/SPLV#efficiency
    - last_visited: '2021-06-06T11:58:34'
      pinned: false
      title: 'SPLV ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/SPLV#overview
    - active: true
      last_visited: '2021-06-06T11:58:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 160
      title: Stock Dividend Calendar | Ex Dividend Pay Date Calendar
      url: https://marketchameleon.com/Calendar/Dividend
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-06T12:19:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Dividend Calendar • 2021 • Updated Daily • Benzinga
      url: https://www.benzinga.com/calendars/dividends
      zoom: 0.75
