windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-01T12:31:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Cheatsheet | Font Awesome
      url: https://fontawesome.com/v5/cheatsheet
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-01T12:31:34'
      pinned: false
      title: web colors - Google Search
      url: https://www.google.com/search?q=web%20colors
    - active: true
      last_visited: '2021-06-01T12:31:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 120
      title: HTML Color Picker
      url: https://www.w3schools.com/colors/colors_picker.asp
      zoom: 0.75
