windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-03T17:48:40'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T17:48:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: google emoji search - Google Search
      url: https://www.google.com/search?q=google%20emoji%20search
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-03T17:48:40'
      pinned: false
      title: tweezer
      url: https://emojipedia.org/search/?q=tweezer
    - last_visited: '2021-06-03T17:54:13'
      pinned: false
      title: cpu
      url: https://emojipedia.org/search/?q=cpu
    - active: true
      last_visited: '2021-06-03T17:55:02'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: folder
      url: https://emojipedia.org/search/?q=folder
      zoom: 0.75
