windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAGQAAACoAAAU8AAAC5gAAAAAAAAAABVYAAAAZAAAA
    KgAABTwAAALm
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-15T13:14:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 256 Colors - Cheat Sheet - Xterm, HEX, RGB, HSL
      url: https://jonasjacek.github.io/colors/
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-15T13:15:30'
      pinned: false
      title: linux pastel - Google Search
      url: https://www.google.com/search?q=linux%20pastel
    - active: true
      last_visited: '2021-06-15T13:15:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 2927
      title: Pastel Is A New Tool To Work With Colors From The Terminal - Linux Uprising
        Blog
      url: https://www.linuxuprising.com/2019/08/pastel-is-new-tool-to-work-with-colors.html
      zoom: 0.75
