windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-03T19:42:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: bash if statement or - Google Search
      url: https://www.google.com/search?q=bash%20if%20statement%20or
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T19:42:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: In a bash script, using the conditional "or" in an "if" statement - Unix
        & Linux Stack Exchange
      url: https://unix.stackexchange.com/questions/47584/in-a-bash-script-using-the-conditional-or-in-an-if-statement
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T19:42:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: i3blocks interval persist - Google Search
      url: https://www.google.com/search?q=i3blocks%20interval%20persist
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-03T19:42:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 2496
      title: 'block with interval=persist does not work as expected · Issue #190 ·
        vivien/i3blocks'
      url: https://github.com/vivien/i3blocks/issues/190
      zoom: 0.75
