windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - last_visited: '2021-05-04T01:05:04'
      pinned: false
      title: MGV ETF Guide | Stock Quote, Holdings, Fact Sheet and More
      url: https://etfdb.com/etf/MGV/#etf-ticker-profile
    - active: true
      last_visited: '2021-05-04T01:05:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: MGV ETF Guide | Stock Quote, Holdings, Fact Sheet and More
      url: https://etfdb.com/etf/MGV/#etf-ticker-profile
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-04T01:05:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: SPIB 36.44 ▼ −0.08% Unnamed
      url: https://www.tradingview.com/chart/vpYiBxKy/
      zoom: 0.75
