windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-05T02:42:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Stock Dividend Calendar | Ex Dividend Pay Date Calendar
      url: https://marketchameleon.com/Calendar/Dividend
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-05T02:42:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Dividend Calendar • 2021 • Updated Daily • Benzinga
      url: https://www.benzinga.com/calendars/dividends
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-05T02:42:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: arrow
      url: https://emojipedia.org/search/?q=arrow
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-05T02:42:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: vim map tab - Google Search
      url: https://www.google.com/search?q=vim%20map%20tab
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-05T02:42:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 200
      title: In vim, how can I remap <tab> without also remapping <Ctrl+i>? - Super
        User
      url: https://superuser.com/questions/770068/in-vim-how-can-i-remap-tab-without-also-remapping-ctrli
      zoom: 0.75
