windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-03T12:35:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Debloat Android – Chris Titus Tech
      url: https://christitus.com/debloat-android/
      zoom: 0.75
