windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-03T18:05:48'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T18:05:48'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: google emoji search - Google Search
      url: https://www.google.com/search?q=google%20emoji%20search
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-06-03T18:05:48'
      pinned: false
      title: meter
      url: https://emojipedia.org/search/?q=meter
    - active: true
      last_visited: '2021-06-03T18:05:54'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: link
      url: https://emojipedia.org/search/?q=link
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T18:05:49'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: cpu symbol - Google Search
      url: https://www.google.com/search?q=cpu%20symbol
      zoom: 0.75
