windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAKwAAABjQAABUoAAAL0AAACsQAAAY4AAAVJAAAC8wAAAAAAAAAABVYAAAKxAAAB
    jgAABUkAAALz
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-15T20:03:19'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: vim startify - Google Search
      url: https://www.google.com/search?q=vim%20startify
      zoom: 0.75
