windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-20T16:02:17'
      pinned: false
      title: vim smoothie plugin - Google Search
      url: https://www.google.com/search?q=vim%20smoothie%20plugin
    - active: true
      last_visited: '2021-05-20T16:02:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: "psliwka/vim-smoothie: Smooth scrolling for Vim done right\U0001F964"
      url: https://github.com/psliwka/vim-smoothie
      zoom: 0.75
