windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - last_visited: '2021-06-01T12:56:59'
      pinned: false
      title: 'Colors not showing in bar · Issue #173 · vivien/i3blocks'
      url: https://github.com/vivien/i3blocks/issues/173
    - active: true
      last_visited: '2021-06-01T12:57:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 1960
      title: 'Color key has no effect. · Issue #146 · vivien/i3blocks'
      url: https://github.com/vivien/i3blocks/issues/146
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-01T13:03:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 440
      title: i3blocks script color - Google Search
      url: https://www.google.com/search?q=i3blocks%20script%20color
      zoom: 0.75
    - last_visited: '2021-06-01T12:57:39'
      pinned: false
      title: colors - i3Blocks script (coloring) - Unix & Linux Stack Exchange
      url: https://unix.stackexchange.com/questions/583409/i3blocks-script-coloring
  - history:
    - active: true
      last_visited: '2021-06-01T13:03:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Can''t figure out how to change the color of i3blocks : i3wm'
      url: https://www.reddit.com/r/i3wm/comments/51rwo2/cant_figure_out_how_to_change_the_color_of/
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-01T13:03:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 880
      title: 'How to specify background color for blocks · Issue #106 · vivien/i3blocks'
      url: https://github.com/vivien/i3blocks/issues/106
      zoom: 0.75
