windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-31T20:52:45'
      pinned: false
      title: Video Previews · ranger/ranger Wiki
      url: https://github.com/ranger/ranger/wiki/Video-Previews
    - last_visited: '2021-05-31T20:52:46'
      pinned: false
      title: Common Changes · ranger/ranger Wiki
      url: https://github.com/ranger/ranger/wiki/Common-Changes
    - active: true
      last_visited: '2021-05-31T20:53:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 3600
      title: Custom Commands · ranger/ranger Wiki
      url: https://github.com/ranger/ranger/wiki/Custom-Commands
      zoom: 0.75
