windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-12T02:17:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: keynav/keynav.pod at master · jordansissel/keynav
      url: https://github.com/jordansissel/keynav/blob/master/keynav.pod
      zoom: 0.75
