windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-04T13:16:16'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Stock Dividend Calendar | Ex Dividend Pay Date Calendar
      url: https://marketchameleon.com/Calendar/Dividend
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-04T14:02:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Dividend Calendar • 2021 • Updated Daily • Benzinga
      url: https://www.benzinga.com/calendars/dividends
      zoom: 0.75
    - last_visited: '2021-06-04T13:57:10'
      pinned: false
      title: Page not found • Benzinga
      url: https://www.benzinga.com/calendars/dividends/search?q=
