windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAADwAABUYAAALwAAAAEAAAABAAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    EAAABUUAAALv
  tabs:
  - active: true
    history:
    - last_visited: '2021-07-03T22:22:07'
      pinned: false
      title: daviwil (David Wilson)
      url: https://github.com/daviwil
    - active: true
      last_visited: '2021-07-03T22:22:46'
      pinned: false
      scroll-pos:
        x: 0
        y: 917
      title: 'daviwil/emacs-from-scratch: An example of a fully custom Emacs configuration
        developed live on YouTube!'
      url: https://github.com/daviwil/emacs-from-scratch
      zoom: 0.75
    - last_visited: '2021-07-03T22:22:44'
      pinned: false
      title: daviwil/emacs-from-scratch at 1a13fcf0dd6afb41fce71bf93c5571931999fed8
      url: https://github.com/daviwil/emacs-from-scratch/tree/1a13fcf0dd6afb41fce71bf93c5571931999fed8
