windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAKyAAAAIAAABUYAAALwAAACsgAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAKyAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-07T22:23:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: keynav/keynavrc.jordan at master · jordansissel/keynav
      url: https://github.com/jordansissel/keynav/blob/master/examples/keynavrc.jordan
      zoom: 0.75
