windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAAEAAAACEAAAKiAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAAAqIAAALv
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-20T17:55:17'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Inbox (9) - markbojack.si@gmail.com - Gmail
      url: https://mail.google.com/mail/u/0/#inbox
      zoom: 0.75
