windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-04T16:15:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'SPY ETF: SPDR S&P 500 ETF - USD | Financial Times'
      url: https://etf.ft.com/funds/4942/
      zoom: 0.75
