windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-07T00:16:24'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - active: true
    history:
    - last_visited: '2021-05-07T00:16:26'
      pinned: false
      title: pamac no confirm aur - Google Search
      url: https://www.google.com/search?q=pamac%20no%20confirm%20aur
    - last_visited: '2021-05-07T00:20:53'
      pinned: false
      title: pamac.conf - Google Search
      url: https://www.google.com/search?q=pamac.conf&ei=aSSUYPnNDNHYhwPN6KDICg&oq=pamac.conf&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEB4yBAgAEB4yBggAEAgQHjIECAAQHjoCCAA6BggAEBYQHjoICC4QxwEQrwE6BQgAEJECOgQIABAKOgYIABAFEB46BAgAEA06BggAEA0QHlCylhBY_aUQYK-nEGgAcAJ4AIABnwGIAeEJkgEEMTIuMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwi5ptnEx7XwAhVR7GEKHU00CKkQ4dUDCA4&uact=5
    - last_visited: '2021-05-07T00:21:06'
      pinned: false
      title: where is pamac.conf - Google Search
      url: https://www.google.com/search?q=where+is+pamac.conf&ei=dSWUYKu8E8KsoATLr5fwBw&oq=where+is+pamac.conf&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEB46BggAEAcQHjoGCAAQDRAeOggIABAIEA0QHlCMTFikVmDNV2gAcAB4AIABf4gBiQeSAQM4LjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=gws-wiz&ved=0ahUKEwjrysXEyLXwAhVCFogKHcvXBX4Q4dUDCA4&uact=5
    - active: true
      last_visited: '2021-05-07T00:41:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 132
      title: pamac/pamac.conf at master · manjaro/pamac
      url: https://github.com/manjaro/pamac/blob/master/data/config/pamac.conf
      zoom: 0.75
    - last_visited: '2021-05-07T00:39:29'
      pinned: false
      title: where put pamac.conf - Google Search
      url: https://www.google.com/search?q=where%20put%20pamac.conf
