windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAAEAAAACEAAAKiAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAAAqIAAALv
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-07-01T23:54:49'
      pinned: false
      scroll-pos:
        x: 0
        y: 360
      title: Internal and external storage - Termux Wiki
      url: https://wiki.termux.com/wiki/Internal_and_external_storage
      zoom: 0.75
