windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-06-17T11:29:42'
      pinned: false
      title: markbojack (Mark Bojack)
      url: https://github.com/markbojack
    - last_visited: '2021-06-17T11:29:47'
      pinned: false
      title: markbojack/dotfiles
      url: https://github.com/markbojack/dotfiles
    - last_visited: '2021-06-17T11:29:47'
      pinned: false
      title: dotfiles/.config at main · markbojack/dotfiles
      url: https://github.com/markbojack/dotfiles/tree/main/.config
    - last_visited: '2021-06-17T11:29:57'
      pinned: false
      title: dotfiles/.config/i3 at main · markbojack/dotfiles
      url: https://github.com/markbojack/dotfiles/tree/main/.config/i3
    - active: true
      last_visited: '2021-06-17T11:30:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 4800
      title: dotfiles/config at main · markbojack/dotfiles
      url: https://github.com/markbojack/dotfiles/blob/main/.config/i3/config
      zoom: 0.75
