windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - active: true
    history:
    - last_visited: '2021-05-18T22:02:29'
      pinned: false
      title: How To Deal With Drawdowns – Quantified Strategies
      url: https://www.quantifiedstrategies.com/how-to-deal-with-drawdowns/
    - active: true
      last_visited: '2021-05-18T22:27:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 4560
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
