windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - history:
    - last_visited: '2021-05-04T00:30:19'
      pinned: false
      title: MGV ETF Guide | Stock Quote, Holdings, Fact Sheet and More
      url: https://etfdb.com/etf/MGV/#etf-ticker-profile
    - active: true
      last_visited: '2021-05-04T00:30:22'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: MGV ETF Guide | Stock Quote, Holdings, Fact Sheet and More
      url: https://etfdb.com/etf/MGV/#etf-ticker-profile
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-04T00:30:47'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: HYD 62.44 ▼ −0.38% Unnamed
      url: https://www.tradingview.com/chart/vpYiBxKy/
      zoom: 0.75
