windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - active: true
    history:
    - last_visited: '2021-06-25T19:04:38'
      pinned: false
      title: Queries (Mu4e 1.4.12 user manual)
      url: https://www.djcbsoftware.nl/code/mu/mu4e/Queries.html
    - active: true
      last_visited: '2021-06-25T19:06:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 1380
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
