windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAKwAAAAGQAABUoAAAF6AAACsgAAABsAAAVIAAABeAAAAAAAAAAABVYAAAKyAAAA
    GwAABUgAAAF4
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-16T18:24:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 4485
      title: Configuration · polybar/polybar Wiki
      url: https://github.com/polybar/polybar/wiki/Configuration
      zoom: 0.75
