windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-05-01T20:09:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Debloat Android – Chris Titus Tech
      url: https://christitus.com/debloat-android/
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-01T20:09:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: i3 numlock startup - Google Search
      url: https://www.google.com/search?q=i3%20numlock%20startup
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-01T20:09:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Num lock keyboard LED light to turn on on startup : i3wm'
      url: https://www.reddit.com/r/i3wm/comments/4acmok/num_lock_keyboard_led_light_to_turn_on_on_startup/
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-05-01T20:09:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'trizen/youtube-viewer: Lightweight YouTube client for Linux'
      url: https://github.com/trizen/youtube-viewer
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-01T20:09:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: My Manjaro i3 setup - Tech Knowledge Base - jaytaala.com Confluence
      url: https://confluence.jaytaala.com/display/TKB/My+Manjaro+i3+setup
      zoom: 0.75
