windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - history:
    - active: true
      last_visited: '2021-07-05T22:29:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'daviwil/emacs-from-scratch: An example of a fully custom Emacs configuration
        developed live on YouTube!'
      url: https://github.com/daviwil/emacs-from-scratch
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-07-05T22:29:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: daviwil/emacs-from-scratch at 3075158cae210060888001c0d76a58a4178f6a00
      url: https://github.com/daviwil/emacs-from-scratch/tree/3075158cae210060888001c0d76a58a4178f6a00
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-07-05T22:29:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: emacs-from-scratch/Emacs-Tips-DisplayBuffer-1.org at master · daviwil/emacs-from-scratch
      url: https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-Tips-DisplayBuffer-1.org
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-07-05T22:29:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: dotfiles/Emacs.org at master · daviwil/dotfiles
      url: https://github.com/daviwil/dotfiles/blob/master/Emacs.org
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-07-05T22:29:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: exwm logout - Google Search
      url: https://www.google.com/search?q=exwm+logout&ei=GB3jYLObDcqf9QP9obvgAQ&oq=exwm+logout&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA06BggAEA0QHjoICAAQDRAFEB46BggAEBYQHjoCCAA6BQghEKABOgYIABANEApKBAhBGABQqUhY0Fdgl1loAXACeACAAYUBiAH9CJIBBDExLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=gws-wiz&ved=0ahUKEwizh8vVl8zxAhXKT30KHf3QDhwQ4dUDCA4&uact=5
      zoom: 0.75
