windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-07T04:10:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 569850-street_light-winter-snow-warm-depth_of_field.jpg (3840×2160)
      url: https://wallup.net/wp-content/uploads/2018/09/25/569850-street_light-winter-snow-warm-depth_of_field.jpg
      zoom: 0.75
