windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAAEAAAACEAAAKiAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAAAqIAAALv
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-06-29T03:23:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 6670
      title: Doom Emacs Configuration
      url: https://tecosaur.github.io/emacs-config/config.html
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-29T04:02:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 72710
      title: Doom Emacs Configuration
      url: https://tecosaur.github.io/emacs-config/config.html#rebuild-mail-index
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-29T03:23:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: zzamboni.org | My Doom Emacs configuration, with commentary
      url: https://zzamboni.org/post/my-doom-emacs-configuration-with-commentary/
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-29T03:23:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: https://raw.githubusercontent.com/zzamboni/dot-doom/master/doom.org
      url: https://raw.githubusercontent.com/zzamboni/dot-doom/master/doom.org
      zoom: 0.75
