windows:
- geometry: !!binary |
    AdnQywADAAAAAAAQAAAAIQAABUUAAALvAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - history: []
  - active: true
    history: []
