windows:
- geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-06T01:25:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'HAP ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/HAP
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-06T01:25:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'FTCS ETF Report: Ratings, Analysis, Quotes, Holdings | ETF.com'
      url: https://www.etf.com/FTCS
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-06T01:25:57'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: HEQ John Hancock Hedged Equity & Income Fund Stock Quote
      url: https://finviz.com/quote.ashx?t=heq
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-06T01:25:57'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: PCM PCM Fund Inc. Stock Quote
      url: https://finviz.com/quote.ashx?t=pcm
      zoom: 0.75
  - history:
    - last_visited: '2021-06-06T01:26:02'
      pinned: false
      title: Yahoo Finance - Stock Market Live, Quotes, Business & Finance News
      url: https://finance.yahoo.com/
    - active: true
      last_visited: '2021-06-06T01:26:20'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'ANTM 393.20 -2.44 -0.62% : Anthem, Inc. - Yahoo Finance'
      url: https://finance.yahoo.com/quote/ANTM?p=ANTM&.tsrc=fin-srch
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-06T01:26:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ANTM 393.20 ▼ −0.62% Unnamed
      url: https://www.tradingview.com/chart/vpYiBxKy/
      zoom: 0.75
