windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-03T23:53:38'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-03T23:53:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: change dmenu font i3 - Google Search
      url: https://www.google.com/search?q=change%20dmenu%20font%20i3
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-03T23:53:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 600
      title: configuration - Custom font with dmenu_run in i3 - Unix & Linux Stack
        Exchange
      url: https://unix.stackexchange.com/questions/287391/custom-font-with-dmenu-run-in-i3
      zoom: 0.75
