windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAAEAAAACEAAAVFAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAABUUAAALv
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-07-04T13:47:50'
      pinned: false
      scroll-pos:
        x: 0
        y: 880
      title: 'daviwil/emacs-from-scratch: An example of a fully custom Emacs configuration
        developed live on YouTube!'
      url: https://github.com/daviwil/emacs-from-scratch
      zoom: 0.75
