windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAADwAAACAAAAKjAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAAAqMAAALw
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2021-05-01T20:09:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Debloat Android – Chris Titus Tech
      url: https://christitus.com/debloat-android/
      zoom: 0.75
