windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAAAqMAAALwAAAAEAAAACEAAAKiAAAC7wAAAAAAAAAABVYAAAAQAAAA
    IQAAAqIAAALv
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-28T10:04:46'
      pinned: false
      scroll-pos:
        x: 0
        y: 6480
      title: Doom Emacs Configuration
      url: https://tecosaur.github.io/emacs-config/config.html
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-28T10:51:47'
      pinned: false
      scroll-pos:
        x: 0
        y: 799
      title: dotemacs/dotemacs.org at master · angrybacon/dotemacs
      url: https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org#use-better-defaults
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-06-28T11:54:52'
      pinned: false
      scroll-pos:
        x: 0
        y: 520
      title: zzamboni.org | My Doom Emacs configuration, with commentary
      url: https://zzamboni.org/post/my-doom-emacs-configuration-with-commentary/
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-28T11:56:29'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: zzamboni.org | literateconfig
      url: https://zzamboni.org/tags/literateconfig/
      zoom: 0.75
  - history:
    - last_visited: '2021-06-28T11:56:38'
      pinned: false
      title: dot-doom/doom.org at master · zzamboni/dot-doom
      url: https://github.com/zzamboni/dot-doom/blob/master/doom.org
    - active: true
      last_visited: '2021-06-28T11:57:27'
      original-url: https://github.com/zzamboni/dot-doom/raw/master/doom.org
      pinned: false
      scroll-pos:
        x: 0
        y: 2360
      title: https://raw.githubusercontent.com/zzamboni/dot-doom/master/doom.org
      url: https://raw.githubusercontent.com/zzamboni/dot-doom/master/doom.org
      zoom: 0.75
  - history:
    - active: true
      last_visited: '2021-06-28T11:55:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 80
      title: 'Doom emacs literate config : emacs'
      url: https://www.reddit.com/r/emacs/comments/empzmz/doom_emacs_literate_config/
      zoom: 0.75
