windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAPAAAAIAAABUYAAALwAAAADwAAACAAAAVGAAAC8AAAAAAAAAAABVYAAAAPAAAA
    IAAABUYAAALw
  tabs:
  - history:
    - last_visited: '2021-05-18T18:23:24'
      pinned: false
      title: Outlook
      url: https://outlook.live.com/mail/0/inbox
    - active: true
      last_visited: '2021-05-18T18:54:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Home
      url: file:///home/mark/p-dot-script/qutebrowser/html/homepage.html
      zoom: 0.75
  - active: true
    history:
    - active: true
      last_visited: '2021-05-18T18:44:49'
      pinned: false
      scroll-pos:
        x: 0
        y: 601
      title: Frequently Asked Questions | Accounts - HSBC VN
      url: https://www.hsbc.com.vn/en-vn/accounts/faq/
      zoom: 0.75
