#+TITLE: Doom Emacs Config
#+AUTHOR: Mark Bojack
#+EMAIL: markbojack@outlook.com
#+date: @@html:<!--@@{{{git-rev}}}@@html:-->@@@@latex:\\\Large\bfseries@@ {{{modification-time(%Y-%m-%d, t)}}} @@latex:\\\normalsize\mdseries@@{{{modification-time(%H:%M, t)}}} @@latex:\acr{\lowercase{@@{{{timezone}}}@@latex:}}\iffalse@@, {{{git-rev}}}@@latex:\fi@@
#+MACRO: timezone (eval (substring (shell-command-to-string "date +%Z") 0 -1))
#+DESCRIPTION: Personal config.org document for Doom Emacs (v2.0.9)
#+STARTUP: overview
#+PROPERTY: header-args:emacs-lisp :tangle yes :comments link
#+PROPERTY: header-args:shell :tangle "setup.sh"
#+PROPERTY: header-args :tangle no :results silent :eval no-export
#+OPTIONS: coverpage:yes

Alphabetize this later, also TOC?

* Background
** Update Frequency
- Continually maintained on an Arch-based system.
** Credit
- For additional inspiration, or to see how I pasted together this config, check the [[Sources][Sources]] section
** For new users
- This is a literate config, so it generates =init.el= and =packages.el=
- As you know, if =init.el= or =packages.el= are modified, run ~doom/reload~ with =SPC h r r=
- Modifying =config.org=
  + Modifications to this file will be realized after running the edited code block with =C-c C-c=
  + In some cases though, ~doom/restart-and-restore~ (=SPC q r=) will be needed
** Special note on R
- If R fails to work properly for whatever reason, try =SPC q r= as a preliminary measure

* Sources
- [[https://nullprogram.com/blog/2016/12/22/][Chris Wellons]]
- [[https://github.com/daviwil][David Wilson]]
- [[https://gitlab.com/dwt1][Derek Taylor]]
- [[https://github.com/zaiste/][Jakub Neander]]
- [[https://github.com/jwiegley/dot-emacs/][John Wiegley]]
- [[https://github.com/angrybacon/dotemacs][Mathieu Marques]]
- [[https://github.com/sachac][Sacha Chua]]
- [[https://github.com/tecosaur/emacs-config][tecosaur]]

* Speed
According to [[https://nullprogram.com/blog/2016/12/22/][Chris Wellons]], the below makes this config run a little faster.

#+BEGIN_SRC emacs-lisp
;;; config.el -*- lexical-binding: t; -*-
#+END_SRC

A [[https://github.com/daviwil][David Wilson]] trick: "Make gc pauses faster by decreasing the threshold."
David's figure was modified in concordance with the config of [[https://github.com/angrybacon/dotemacs][Mathieu Marques]].

#+BEGIN_SRC emacs-lisp
(setq gc-cons-threshold (* 8 1024 1024))
#+END_SRC

* Mappings
Mostly from [[https://github.com/zaiste/][Jakub Neander]].

#+BEGIN_SRC emacs-lisp
(map! :desc "Create Sparse Tree" :ne "SPC / s" #'org-sparse-tree)
(map! :desc "Create Sparse Tree for Tags" :ne "SPC / t" #'org-tags-sparse-tree)
(map! :ne "M-/" #'comment-or-uncomment-region)
(map! :ne "SPC n r" #'deadgrep)
(map! :ne "SPC n b" #'org-brain-visualize)
(map! :ne "SPC n p" #'counsel-org-capture)
#+END_SRC

* Personal Information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Mark Bojack"
      user-mail-address "markbojack.si@gmail.com")
#+END_SRC

* Defaults
** setq-default
Selected variable settings from [[https://github.com/angrybacon/dotemacs][Mathieu Marques']] "Better Defaults."

#+BEGIN_SRC emacs-lisp
(setq-default cursor-in-non-selected-windows nil     ; Hide the cursor in inactive windows
              custom-unlispify-menu-entries nil      ; Prefer kebab-case for titles
              custom-unlispify-tag-names nil         ; Prefer kebab-case for symbols
              delete-by-moving-to-trash t            ; Delete files to trash
              fill-column 80                         ; Set width for automatic line breaks
              help-window-select t                   ; Focus new help windows when opened
              initial-scratch-message ""             ; Empty the initial *scratch* buffer
              mouse-yank-at-point t                  ; Yank at point rather than pointer
              read-process-output-max (* 1024 1024)  ; Increase read size per process
              recenter-positions '(5 top bottom)     ; Set re-centering positions
              scroll-conservatively 101              ; Avoid recentering when scrolling far
              scroll-margin 2                        ; Add a margin when scrolling vertically
              show-help-function nil                 ; Disable help text everywhere
              tab-always-indent 'complete            ; Tab indents first then tries completions
              tab-width 4                            ; Smaller width for tab characters
              uniquify-buffer-name-style 'forward    ; Better than filename<2> for same-name buffers
              window-combination-resize t            ; Take new window space from all windows (not just current)
              x-stretch-cursor t)                    ; Stretch cursor to the glyph width
#+END_SRC

** setq
TODO https://stackoverflow.com/questions/53769315/emacs-ess-indent-after

#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one
      display-line-numbers-type 'relative
      evil-split-window-below t
      evil-vsplit-window-right t
      auto-save-default t
      make-backup-files t
      ess-indent-offset 2
      confirm-kill-emacs nil
      undo-limit 80000000)
#+END_SRC

* Spelling
Thanks [[https://www.reddit.com/r/emacs/comments/mr3urh/disable_spellfumode_in_doomemacs/][Reddit]]!
Disable spell-fu-mode in Doom Emacs.  Re-add the hook selectively.

#+BEGIN_SRC emacs-lisp
(remove-hook 'text-mode-hook #'spell-fu-mode)
(add-hook 'markdown-mode-hook #'spell-fu-mode)
#+END_SRC

* Font
From [[https://gitlab.com/dwt1][Derek Taylor's]] config:
+ 'doom-font' -- standard monospace font that is used for most things in Emacs.
+ 'doom-variable-pitch-font' -- variable font which is useful in some Emacs plugins.
+ 'doom-big-font' -- used in doom-big-font-mode; useful for presentations.
+ 'font-lock-comment-face' -- for comments.
+ 'font-lock-keyword-face' -- for keywords with special significance like 'setq' in elisp.
+ 'global-prettify-symbols-mode' -- change certain keywords to symbols, such as lambda!

'global-prettify-symbols-mode' note above is retained just for reference.

I can't customize doom-big-font 😭

#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "RobotoMono Nerd Font" :size 10 :weight 'bold)
      ;; doom-big-font (font-spec :family "RobotoMono Nerd Font" :size 14))
      doom-variable-pitch-font (font-spec :family "sans" :size 13))

(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))

(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+END_SRC
