#!/bin/bash

url=$({
	echo "QUICKMARKS ----------------------------------------------------------"
	cat "$QUTE_CONFIG_DIR"/quickmarks
	echo ""
	echo "BOOKMARKS -----------------------------------------------------------"
    cat "$QUTE_CONFIG_DIR"/bookmarks/urls
	echo ""
	echo "HISTORY -------------------------------------------------------------"
    sqlite3 -separator ' ' "$QUTE_DATA_DIR"/history.sqlite 'SELECT url, title FROM CompletionHistory'
} | dmenu -i -l 20 -p "open $* " | awk '{ if ($2 ~ /^http/) print $2; else print }') || exit

[ $? = 0 ] && [ -n "$url" ] && printf 'open %s %s\n' "$*" "$url" >> "$QUTE_FIFO" || echo "Program terminated." && exit 0
