#!/bin/bash

url=$({
	echo "QUICKMARKS ----------------------------------------------------------"
	cat "$QUTE_CONFIG_DIR"/quickmarks
	echo -e "\n"
	echo "BOOKMARKS -----------------------------------------------------------"
    cat "$QUTE_CONFIG_DIR"/bookmarks/urls
	echo -e "\n"
	echo "HISTORY -------------------------------------------------------------"
    sqlite3 -separator ' ' "$QUTE_DATA_DIR"/history.sqlite 'SELECT url, title FROM CompletionHistory'
} | dmenu -l 30 -p "open $* " | awk '{ if ($2 ~ /^http/) print $2; else print }')

[ $? = 0 ] && [ -n "$url" ] && printf 'open %s %s\n' "$*" "$url" >> "$QUTE_FIFO"
